import esbuild from "esbuild";
import process from "process";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Demo build of Obsidian CytoQuery
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/demo/demo-entry.ts"],
	bundle: true,
	external: [], // Bundle everything for standalone use
	format: "iife", // Immediately invoked function expression for browser
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "demo/cytoquery-demo.js",
	minify: prod,
	loader: {
		'.js': 'js',
		'.ts': 'ts'
	}
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}